### PR TITLE
404

### PR DESCRIPTION
**Pull request by DLu**

### CODE REVIEW

**Comment by kscottz** [comment]
I went so far as to try and deploy this on beta.ros.org. While the 404 page seems to be in the right spot, errors don't seem to be routed to it. I am thinking we'll need to go muck with the Apache .htaccess file to make it happen but I want to get a second opinion from @tfoote.

**Comment by DLu** [comment]
Yeah, there was no guide for how to do this, so I was guessing.

**Review by tfoote — APPROVED** [review]
This looks right. We'll have to merge it and then play with the settings to make sure it's picked up.

**Comment by DLu** [comment]
So....merge?

**Comment by DLu** [comment]
Doesn't look to be functional yet: https://www.ros.org/tullysbeard

**Pull request merged**
